spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}

jwt:
  secret: ${JWT_SECRET}

firebase:
  service-account-json: ${FIREBASE_SERVICE_ACCOUNT_JSON:}

logging.level:
  root: INFO
