spring:
  profiles:
    active: local
server:
  port: 8082

sse:
  timeout: 0

management:
  endpoint:
    health:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,prometheus
